### ISSUE TITLE
White List inclusion possible?

### ISSUE THREAD

**Issue by ledern** [kasenoshi/instagram-unfollow#1]
Hello my dear, 
I am a bloody beginner and try this for the second time. Is there any other code existing which is doing exactly the same like unfollowing all but not those I put in the white list?

Thank you and BR, Nadine

**Comment by ledern** [comment]
I got this Syntax error, may you can help me to fix that =)? 
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Nadine2:", end=" ")?

Thank you a lot, I still try to learn. BR, Nadine

**Comment by kasenoshi** [comment]
You are using python3, but my code is for python2.
Anyway, it's been a while since I wrote the code. I'm pretty sure it will not work for current instagram web.
I will try to update it if it's easy.

**Comment by kasenoshi** [comment]
Updated, support skiplist, please get the latest code and follow Readme.
Feel free to drop issue if it does not work.

**Comment by ledern** [comment]
Wow, thank you so much! Amazing, I did not even think I would get an answer and not at all so fast. Thank you so much for your kindness and help. I am exited to go on trying and learning =)! I come back to you and give you feedback of what turned out =]. BR and have a nice evening, Nadine

**Comment by ledern** [comment]
Hello, I tried now for two day but I guess I am too unexperienced. I know you are not a personal trainer. May I still ask you if we can do a 20 min call to go through the steps? I do not know how else I can understand and learn it. Of course I know your time is very precious. If you would tell me how much it would be I can may give you
small expense allowance? Thank you a lot in advance for your quick response. BR, Nadine
